// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJZ1ZlcM7qESZNJq2yFUlMCdlsxjoQT20',
    appId: '1:223478065247:web:336a44197db83e598b13ea',
    messagingSenderId: '223478065247',
    projectId: 'notificationsbackground',
    authDomain: 'notificationsbackground.firebaseapp.com',
    storageBucket: 'notificationsbackground.appspot.com',
    measurementId: 'G-R24F1JFQDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG79a-9sctDJssibXlekMrBEe3NySwKs4',
    appId: '1:223478065247:android:5f79e57d6926bd968b13ea',
    messagingSenderId: '223478065247',
    projectId: 'notificationsbackground',
    storageBucket: 'notificationsbackground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVVkJ9RAe7d2lE008etIOe0ZTW3hnE5Tc',
    appId: '1:223478065247:ios:3d034fefa25f02418b13ea',
    messagingSenderId: '223478065247',
    projectId: 'notificationsbackground',
    storageBucket: 'notificationsbackground.appspot.com',
    iosBundleId: 'com.example.notificationsVideoCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVVkJ9RAe7d2lE008etIOe0ZTW3hnE5Tc',
    appId: '1:223478065247:ios:3d034fefa25f02418b13ea',
    messagingSenderId: '223478065247',
    projectId: 'notificationsbackground',
    storageBucket: 'notificationsbackground.appspot.com',
    iosBundleId: 'com.example.notificationsVideoCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJZ1ZlcM7qESZNJq2yFUlMCdlsxjoQT20',
    appId: '1:223478065247:web:7fc0912e7b93450a8b13ea',
    messagingSenderId: '223478065247',
    projectId: 'notificationsbackground',
    authDomain: 'notificationsbackground.firebaseapp.com',
    storageBucket: 'notificationsbackground.appspot.com',
    measurementId: 'G-Y7N1XTVSCN',
  );
}
